[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# 보안 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://api.ipify.org; frame-ancestors 'none';"

# 환경 변수 설정 (Netlify 대시보드에서 설정)
[context.production.environment]
  VITE_SUPABASE_URL = "your_production_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_production_supabase_anon_key"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "your_preview_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_preview_supabase_anon_key"

# 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 